const tileURLs: { name: string; url: string; img: string; type: string }[] = [
  {
    name: "Mapbox Streets",
    url: "mapbox://styles/mapbox/streets-v11",
    img: "/mapPreview/MapboxStreets.png",
    type: "mapbox",
  },
  {
    name: "Mapbox Satellite",
    url: "mapbox://styles/mapbox/satellite-v9",
    img: "/mapPreview/MapboxSatellite.png",
    type: "mapbox",
  },
  {
    name: "Mapbox Outdoors",
    url: "mapbox://styles/mapbox/outdoors-v11",
    img: "/mapPreview/MapboxOutdoors.png",
    type: "mapbox",
  },
  {
    name: "Mapbox Light",
    url: "mapbox://styles/mapbox/light-v10",
    img: "/mapPreview/MapboxLight.png",
    type: "mapbox",
  },
  {
    name: "Mapbox Dark",
    url: "mapbox://styles/mapbox/dark-v10",
    img: "/mapPreview/MapboxDark.png",
    type: "mapbox",
  },
  {
    name: "Mapbox Navigation Day",
    url: "mapbox://styles/mapbox/navigation-day-v1",
    img: "/mapPreview/MapboxNavigationDay.png",
    type: "mapbox",
  },
  {
    name: "Mapbox Navigation Night",
    url: "mapbox://styles/mapbox/navigation-night-v1",
    img: "/mapPreview/MapboxNavigationNight.png",
    type: "mapbox",
  },
  {
    name: "OpenStreetMap",
    url: "https://api.maptiler.com/maps/openstreetmap/style.json",
    img: "/mapPreview/OpenStreetMap.png",
    type: "standard",
  },
  {
    name: "Positron",
    url: "https://api.maptiler.com/maps/positron/style.json",
    img: "/mapPreview/Positron.png",
    type: "standard",
  },
  {
    name: "Dark Matter",
    url: "https://api.maptiler.com/maps/darkmatter/style.json",
    img: "/mapPreview/DarkMatter.png",
    type: "standard",
  },
  {
    name: "Voyager",
    url: "https://api.maptiler.com/maps/voyager/style.json",
    img: "/mapPreview/Voyager.png",
    type: "standard",
  },
  {
    name: "Hybrid",
    url: "https://api.maptiler.com/maps/hybrid/style.json",
    img: "/mapPreview/Hybrid.png",
    type: "standard",
  },
  {
    name: "Default",
    url: "https://demotiles.maplibre.org/style.json",
    img: "/mapPreview/default.png",
    type: "maplibre",
  },
  {
    name: "aquarelle",
    url: "https://api.maptiler.com/maps/aquarelle/style.json",
    img: "/mapPreview/aquarelle.png",
    type: "standard",
  },
  {
    name: "backdrop",
    url: "https://api.maptiler.com/maps/backdrop/style.json",
    img: "/mapPreview/backdrop.png",
    type: "standard",
  },
  {
    name: "basic",
    url: "https://api.maptiler.com/maps/basic-v2/style.json",
    img: "/mapPreview/basic.png",
    type: "standard",
  },
  {
    name: "bright",
    url: "https://api.maptiler.com/maps/bright-v2/style.json",
    img: "/mapPreview/Bright.png",
    type: "standard",
  },
  {
    name: "dataviz",
    url: "https://api.maptiler.com/maps/dataviz/style.json",
    img: "/mapPreview/Dataviz.png",
    type: "standard",
  },
  {
    name: "landscape",
    url: "https://api.maptiler.com/maps/landscape/style.json",
    img: "/mapPreview/Landscape.png",
    type: "standard",
  },
  {
    name: "toner",
    url: "https://api.maptiler.com/maps/toner-v2/style.json",
    img: "/mapPreview/Toner.png",
    type: "standard",
  },
  {
    name: "streets",
    url: "https://api.maptiler.com/maps/streets-v2/style.json",
    img: "/mapPreview/Streets.png",
    type: "standard",
  },
  {
    name: "satellite",
    url: "https://api.maptiler.com/maps/satellite/style.json",
    img: "/mapPreview/Satellite.png",
    type: "standard",
  },
  {
    name: "outdoor",
    url: "https://api.maptiler.com/maps/outdoor-v2/style.json",
    img: "/mapPreview/Outdoor.png",
    type: "standard",
  },
  {
    name: "winter",
    url: "https://api.maptiler.com/maps/winter-v2/style.json",
    img: "/mapPreview/Winter.png",
    type: "standard",
  },
  {
    name: "topo",
    url: "https://api.maptiler.com/maps/topo-v2/style.json",
    img: "/mapPreview/Topo.png",
    type: "standard",
  },
  {
    name: "ocean",
    url: "https://api.maptiler.com/maps/ocean/style.json",
    img: "/mapPreview/Ocean.png",
    type: "standard",
  },
  {
    name: "openstreetmap New",
    url: "https://api.maptiler.com/maps/openstreetmap/style.json",
    img: "/mapPreview/OpenStreetMapNew.png",
    type: "standard",
  },
  {
    name: "Experimental",
    url: "https://api.maptiler.com/maps/01992e84-a740-7c52-90b2-2ad2e7ab5555/style.json",
    img: "/mapPreview/Experimental.png",
    type: "experimental",
  },
];

export default tileURLs;
